version: '3.4'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 54320:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: