[tool.poetry]
name = "de_day00"
version = "1.0"
description = ""
authors = ["fbabin fbabin@student.42.fr"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "*"
numpy = "*"
pandas = "*"
psycopg2 = "*"

#sudo apt install postgresql libpq-dev